### ISSUE TITLE
Add more carbon

### ISSUE THREAD

**Issue by aaronspring** [aaronspring/remote_climate_data#47]
https://www.bgc-jena.mpg.de/SOCOM/

**Comment by aaronspring** [comment]
Also land carbon:

https://www.nature.com/articles/s41597-020-00653-5

**Comment by aaronspring** [comment]
Add obs4mip CO2 and ch4

**Comment by aaronspring** [comment]
And land carbon see https://github.com/rubisco-sfa/ILAMB-Data/tree/master

**Comment by aaronspring** [comment]
Eppley http://orca.science.oregonstate.edu/data/1x2/monthly/eppley.r2018.m.chl.m.sst/hdf

**Comment by aaronspring** [comment]
https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:0220059

**Comment by aaronspring** [comment]
https://www.nature.com/articles/s41597-020-00779-6

**Comment by aaronspring** [comment]
che-project.eu/data-portal

**Comment by luke-gregor** [comment]
- NIES-NN: https://db.cger.nies.go.jp/DL/10.17595/20201020.001.html.en 
- JMA-MLR (zipped): http://www.data.jma.go.jp/gmd/kaiyou/english/co2_flux/co2_flux_data_en.html

Other data sets
http://www.bgc-jena.mpg.de/SOCOM/Methods.html

**Comment by aaronspring** [comment]
this is how zipped sources are (cached and) unzipped https://github.com/aaronspring/remote_climate_data/blob/650cfa774f3b83f065d3ff2fe1fa0c86e7d430be/catalogs/ocean.yaml#L26

**Comment by aaronspring** [comment]
Land carbon https://www.bgc-jena.mpg.de/CarboScope/?ID=oc

**Comment by aaronspring** [comment]
Emissions and land use https://www.nature.com/articles/sdata2018210

**Comment by aaronspring** [comment]
Try get fluxcom https://www.bgc-jena.mpg.de/geodb/projects/FileDetails.php

**Comment by aaronspring** [comment]
http://c4mip.net/cmip6-experiments
